name: CandorChannels
version: ${project.version}
main: xyz.directplan.candorchannels.CandorChannel
api-version: 1.16
authors: [ DirectPlan ]
description: A simple spigot channels plugin tasked by Candor Services to pass the freelancer test  
